# Generated by Django 2.2.6 on 2019-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='populationsearch',
            name='no_of_female',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='populationsearch',
            name='no_of_male',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='cityorstate',
            constraint=models.UniqueConstraint(fields=('country', 'city_or_state'), name='unique_country_state'),
        ),
    ]
