# Generated by Django 2.2.6 on 2019-10-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_search', '0002_auto_20191024_1557'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='populationsearch',
            constraint=models.UniqueConstraint(fields=('group', 'no_of_male', 'no_of_female'), name='unique_group_age'),
        ),
    ]
