# Generated by Django 2.2.6 on 2019-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_search', '0003_auto_20191031_0542'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='populationsearch',
            name='unique_group_age',
        ),
        migrations.AddConstraint(
            model_name='populationsearch',
            constraint=models.UniqueConstraint(fields=('group', 'no_of_male', 'no_of_female', 'city_or_state'), name='unique_group_age_state'),
        ),
    ]
