# Generated by Django 2.2.6 on 2019-10-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_search', '0004_auto_20191031_0544'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='populationsearch',
            name='unique_group_age_state',
        ),
        migrations.AddConstraint(
            model_name='populationsearch',
            constraint=models.UniqueConstraint(fields=('group', 'country', 'city_or_state'), name='unique_group_age_state'),
        ),
    ]
